"""initial schema — full FörderFlow data model (46 tables, 24 enums)

Baseline migration. Builds the complete original FörderFlow schema as a *pinned*
set of explicit DDL statements, captured once from the SQLAlchemy metadata at the
0001 point in time (46 tables, 24 native enum types). It is intentionally NOT
derived from ``Base.metadata.create_all()`` at runtime: doing so made the baseline
track the *live* models, so PCM tables/columns/enums added in 0002+ leaked into
0001 and collided with the very migrations meant to create them (DuplicateTable).

The statements below are emitted in dependency order (enum types, then tables,
then any deferred foreign keys), exactly as ``create_all`` produced them, so the
resulting database stays byte-compatible with the original FörderFlow schema and
the monolith's Prisma ``@@map`` names. To regenerate after intentionally changing
the baseline, re-run the offline DDL dump that produced this file.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-16
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_CREATE_STATEMENTS: tuple[str, ...] = (
    "CREATE TYPE allocation_basis AS ENUM ('MITARBEITERZAHL', 'QUADRATMETER', 'BUDGET_ANTEIL', 'MANUELL')",
    "CREATE TYPE org_role AS ENUM ('ADMIN', 'FINANCE', 'READONLY')",
    "CREATE TYPE eigenanteil_typ AS ENUM ('KOFINANZIERUNG', 'NICHT_FOERDERFAHIGER_OVERHEAD')",
    "CREATE TYPE pauschale_typ AS ENUM ('FIXER_BETRAG', 'PROZENT_GESAMT', 'PROZENT_PERSONAL', 'UMLAGE_KOSTENSTELLEN')",
    "CREATE TYPE verwendungsnachweis_typ AS ENUM ('ZWISCHENNACHWEIS', 'VERWENDUNGSNACHWEIS', 'SACHBERICHT_ONLY')",
    "CREATE TYPE verwendungsnachweis_status AS ENUM ('OFFEN', 'IN_BEARBEITUNG', 'EINGEREICHT', 'ANERKANNT', 'ABGELEHNT')",
    "CREATE TYPE mittelabruf_verfahren AS ENUM ('ANFORDERUNG', 'ABRUF', 'ABSCHLAG')",
    "CREATE TYPE funding_measure_status AS ENUM ('AKTIV', 'ABGESCHLOSSEN', 'WIDERRUFEN')",
    "CREATE TYPE finanzierungsart_typ AS ENUM ('ANTEIL', 'FEHLBEDARF', 'FESTBETRAG')",
    "CREATE TYPE bescheid_quelle AS ENUM ('OCR_IMPORT', 'MANUAL_UPLOAD')",
    "CREATE TYPE funding_rule_typ AS ENUM ('KOSTENKATEGORIE_ERLAUBT', 'KOSTENKATEGORIE_VERBOTEN', 'BELEGPFLICHT_SPEZIAL', 'EIGENANTEIL_MIN', 'VERWENDUNGSFRIST_TAGE', 'ZWISCHENNACHWEIS_PFLICHT', 'PERSONALKOSTEN_HOECHSTSATZ')",
    "CREATE TYPE cost_center_typ AS ENUM ('PROJECT', 'OVERHEAD')",
    "CREATE TYPE funder_typ AS ENUM ('STIFTUNG', 'KOMMUNE', 'MINISTERIUM', 'EU', 'ANDERE', 'KIRCHE', 'PRIVAT')",
    "CREATE TYPE frist_bezug AS ENUM ('HHJ_ENDE', 'DURCHFUEHRUNG_ENDE', 'BEWILLIGUNG_ENDE')",
    "CREATE TYPE fiscal_year_status AS ENUM ('OFFEN', 'GESCHLOSSEN')",
    "CREATE TYPE mittelabruf_status AS ENUM ('ABGERUFEN', 'VERWENDET', 'ABGELAUFEN', 'ZURUECKGEZAHLT')",
    "CREATE TYPE rechtsform AS ENUM ('EV', 'GGMBH', 'STIFTUNG', 'ANDERE')",
    "CREATE TYPE vertragsart AS ENUM ('FESTANSTELLUNG', 'MINIJOB', 'WERKVERTRAG', 'EHRENAMT')",
    "CREATE TYPE tarifwerk AS ENUM ('TVOEDD', 'TVOEL', 'AVR_CARITAS', 'AVR_DD', 'INDIVIDUELL')",
    "CREATE TYPE salary_component_typ AS ENUM ('FESTBEZUG', 'VWL_AG_ZUSCHUSS', 'JOBTICKET_SACHBEZUG', 'SALARY_ADJUSTMENT', 'SONSTIGES')",
    "CREATE TYPE account_typ AS ENUM ('BANK', 'KASSE', 'ONLINE_WALLET')",
    "CREATE TYPE import_format AS ENUM ('GENERIC_CSV', 'FINOM_CSV', 'SPARKASSE_CSV', 'CAMT_053', 'DATEV_CSV', 'MANUELL')",
    "CREATE TYPE transaction_typ AS ENUM ('AUSGABE', 'EINNAHME', 'INTERNE_UMBUCHUNG')",
    "CREATE TYPE transaction_status AS ENUM ('IMPORTIERT', 'KATEGORISIERT', 'ZUGEORDNET', 'ABGESCHLOSSEN')",
    'CREATE TABLE audit_logs (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tuser_id VARCHAR, \n\taktion VARCHAR(100) NOT NULL, \n\tentitaet VARCHAR(100) NOT NULL, \n\tentitaet_id VARCHAR(200) NOT NULL, \n\tvorher JSONB, \n\tnachher JSONB, \n\tip VARCHAR(100), \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_audit_logs PRIMARY KEY (id)\n)',
    'CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at)',
    'CREATE INDEX ix_audit_logs_org_id_user_id ON audit_logs (org_id, user_id)',
    'CREATE INDEX ix_audit_logs_org_id ON audit_logs (org_id)',
    'CREATE INDEX ix_audit_logs_org_id_entitaet ON audit_logs (org_id, entitaet)',
    'CREATE TABLE organizations (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\trechtsform rechtsform NOT NULL, \n\tregelarbeitszeit_stunden NUMERIC(4, 2) NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_organizations PRIMARY KEY (id)\n)',
    'CREATE TABLE tarif_tabelle (\n\tid VARCHAR NOT NULL, \n\ttarifwerk tarifwerk NOT NULL, \n\tentgeltgruppe VARCHAR(20) NOT NULL, \n\tstufe INTEGER NOT NULL, \n\tjahr INTEGER NOT NULL, \n\tbetrag NUMERIC(14, 2) NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_tarif_tabelle PRIMARY KEY (id), \n\tCONSTRAINT uq_tarif_tabelle_tarifwerk UNIQUE (tarifwerk, entgeltgruppe, stufe, jahr)\n)',
    'CREATE INDEX ix_tarif_tabelle_tarifwerk_jahr ON tarif_tabelle (tarifwerk, jahr)',
    "CREATE TABLE users (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR, \n\tvorname VARCHAR(100), \n\tnachname VARCHAR(100), \n\temail VARCHAR NOT NULL, \n\temail_verified TIMESTAMP WITHOUT TIME ZONE, \n\timage VARCHAR, \n\tis_super_admin BOOLEAN DEFAULT 'false' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_users PRIMARY KEY (id), \n\tCONSTRAINT uq_users_email UNIQUE (email)\n)",
    'CREATE TABLE verification_tokens (\n\tidentifier VARCHAR NOT NULL, \n\ttoken VARCHAR NOT NULL, \n\texpires TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tCONSTRAINT pk_verification_tokens PRIMARY KEY (token), \n\tCONSTRAINT uq_verification_tokens_identifier UNIQUE (identifier, token), \n\tCONSTRAINT uq_verification_tokens_token UNIQUE (token)\n)',
    'CREATE TABLE accounts (\n\tid VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\ttype VARCHAR NOT NULL, \n\tprovider VARCHAR NOT NULL, \n\tprovider_account_id VARCHAR NOT NULL, \n\trefresh_token TEXT, \n\taccess_token TEXT, \n\texpires_at INTEGER, \n\ttoken_type VARCHAR, \n\tscope VARCHAR, \n\tid_token TEXT, \n\tsession_state VARCHAR, \n\tCONSTRAINT pk_accounts PRIMARY KEY (id), \n\tCONSTRAINT uq_accounts_provider UNIQUE (provider, provider_account_id), \n\tCONSTRAINT fk_accounts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_accounts_user_id ON accounts (user_id)',
    "CREATE TABLE allocation_keys (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tbasis allocation_basis NOT NULL, \n\tgueltig_von DATE NOT NULL, \n\tgueltig_bis DATE, \n\tist_aktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tparent_key_id VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_allocation_keys PRIMARY KEY (id), \n\tCONSTRAINT fk_allocation_keys_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_allocation_keys_parent_key_id_allocation_keys FOREIGN KEY(parent_key_id) REFERENCES allocation_keys (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_allocation_keys_org_id ON allocation_keys (org_id)',
    'CREATE INDEX ix_allocation_keys_org_id_gueltig_von_gueltig_bis ON allocation_keys (org_id, gueltig_von, gueltig_bis)',
    'CREATE INDEX ix_allocation_keys_parent_key_id ON allocation_keys (parent_key_id)',
    'CREATE INDEX ix_allocation_keys_org_id_ist_aktiv ON allocation_keys (org_id, ist_aktiv)',
    "CREATE TABLE bank_accounts (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tcode VARCHAR(50) NOT NULL, \n\tbezeichnung VARCHAR(120) NOT NULL, \n\ttyp account_typ NOT NULL, \n\tiban VARCHAR(34), \n\tbic VARCHAR(11), \n\tbankname VARCHAR(120), \n\tist_aktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_bank_accounts PRIMARY KEY (id), \n\tCONSTRAINT uq_bank_accounts_org_id UNIQUE (org_id, code), \n\tCONSTRAINT fk_bank_accounts_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_bank_accounts_iban UNIQUE (iban)\n)",
    'CREATE INDEX ix_bank_accounts_org_id ON bank_accounts (org_id)',
    'CREATE INDEX ix_bank_accounts_org_id_ist_aktiv ON bank_accounts (org_id, ist_aktiv)',
    "CREATE TABLE cost_centers (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tcode VARCHAR NOT NULL, \n\ttyp cost_center_typ NOT NULL, \n\tist_aktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tparent_id VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_cost_centers PRIMARY KEY (id), \n\tCONSTRAINT uq_cost_centers_org_id UNIQUE (org_id, code), \n\tCONSTRAINT fk_cost_centers_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_cost_centers_parent_id_cost_centers FOREIGN KEY(parent_id) REFERENCES cost_centers (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_cost_centers_org_id ON cost_centers (org_id)',
    'CREATE INDEX ix_cost_centers_org_id_ist_aktiv ON cost_centers (org_id, ist_aktiv)',
    'CREATE TABLE csv_import_profiles (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR, \n\tname VARCHAR(120) NOT NULL, \n\tbeschreibung TEXT, \n\tdelimiter VARCHAR(4) NOT NULL, \n\tencoding VARCHAR(20) NOT NULL, \n\tquote_char VARCHAR(2) DEFAULT \'"\' NOT NULL, \n\tdecimal_separator VARCHAR(1) NOT NULL, \n\tthousand_separator VARCHAR(1), \n\tdate_format VARCHAR(20) NOT NULL, \n\theader_row INTEGER DEFAULT \'1\' NOT NULL, \n\tskip_rows INTEGER DEFAULT \'0\' NOT NULL, \n\tcolumn_mappings JSONB NOT NULL, \n\tauto_detect_pattern VARCHAR(255), \n\tist_systemweit BOOLEAN DEFAULT \'false\' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_csv_import_profiles PRIMARY KEY (id), \n\tCONSTRAINT uq_csv_import_profiles_org_id UNIQUE (org_id, name), \n\tCONSTRAINT fk_csv_import_profiles_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_csv_import_profiles_ist_systemweit ON csv_import_profiles (ist_systemweit)',
    'CREATE INDEX ix_csv_import_profiles_auto_detect_pattern ON csv_import_profiles (auto_detect_pattern)',
    'CREATE INDEX ix_csv_import_profiles_org_id ON csv_import_profiles (org_id)',
    "CREATE TABLE employees (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\temployee_code VARCHAR(50) NOT NULL, \n\tvorname VARCHAR NOT NULL, \n\tnachname VARCHAR NOT NULL, \n\temail VARCHAR(255), \n\teintrittsdatum DATE NOT NULL, \n\taustrittsdatum DATE, \n\tist_aktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_employees PRIMARY KEY (id), \n\tCONSTRAINT uq_employees_org_id UNIQUE (org_id, employee_code), \n\tCONSTRAINT fk_employees_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_employees_org_id ON employees (org_id)',
    'CREATE INDEX ix_employees_org_id_ist_aktiv ON employees (org_id, ist_aktiv)',
    'CREATE TABLE employer_gross_factors (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tvertragsart vertragsart NOT NULL, \n\tfaktor NUMERIC(6, 4) NOT NULL, \n\tgueltig_ab DATE NOT NULL, \n\tgueltig_bis DATE, \n\tnotiz TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_employer_gross_factors PRIMARY KEY (id), \n\tCONSTRAINT fk_employer_gross_factors_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_employer_gross_factors_org_id ON employer_gross_factors (org_id)',
    'CREATE INDEX ix_employer_gross_factors_org_id_vertragsart_gueltig_ab ON employer_gross_factors (org_id, vertragsart, gueltig_ab)',
    "CREATE TABLE fiscal_years (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tjahr INTEGER NOT NULL, \n\tbeginn DATE NOT NULL, \n\tende DATE NOT NULL, \n\tstatus fiscal_year_status DEFAULT 'OFFEN' NOT NULL, \n\tgeschlossen_am TIMESTAMP WITHOUT TIME ZONE, \n\tgeschlossen_von VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_fiscal_years PRIMARY KEY (id), \n\tCONSTRAINT uq_fiscal_years_org_id UNIQUE (org_id, jahr), \n\tCONSTRAINT fk_fiscal_years_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_fiscal_years_org_id ON fiscal_years (org_id)',
    'CREATE INDEX ix_fiscal_years_org_id_status ON fiscal_years (org_id, status)',
    'CREATE TABLE funders (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\ttyp funder_typ NOT NULL, \n\tnotizen TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_funders PRIMARY KEY (id), \n\tCONSTRAINT fk_funders_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_funders_org_id ON funders (org_id)',
    'CREATE INDEX ix_funders_org_id_typ ON funders (org_id, typ)',
    "CREATE TABLE kostenbereiche (\n\tid VARCHAR NOT NULL, \n\tcode VARCHAR(50) NOT NULL, \n\tbezeichnung VARCHAR(200) NOT NULL, \n\tbeschreibung TEXT, \n\tparent_id VARCHAR, \n\torg_id VARCHAR, \n\tist_aktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tskr42_konto_von VARCHAR(20), \n\tskr42_konto_bis VARCHAR(20), \n\tist_personal BOOLEAN DEFAULT 'false' NOT NULL, \n\tist_gemeinkosten BOOLEAN DEFAULT 'false' NOT NULL, \n\tbelegpflicht_default BOOLEAN DEFAULT 'true' NOT NULL, \n\tfoerderfahig_default BOOLEAN DEFAULT 'true' NOT NULL, \n\tsort_order INTEGER DEFAULT '0' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_kostenbereiche PRIMARY KEY (id), \n\tCONSTRAINT uq_kostenbereiche_code UNIQUE (code), \n\tCONSTRAINT fk_kostenbereiche_parent_id_kostenbereiche FOREIGN KEY(parent_id) REFERENCES kostenbereiche (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_kostenbereiche_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE CASCADE\n)",
    'CREATE INDEX ix_kostenbereiche_parent_id ON kostenbereiche (parent_id)',
    'CREATE INDEX ix_kostenbereiche_org_id ON kostenbereiche (org_id)',
    'CREATE INDEX ix_kostenbereiche_ist_aktiv ON kostenbereiche (ist_aktiv)',
    "CREATE TABLE org_invites (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\temail VARCHAR NOT NULL, \n\trole org_role DEFAULT 'FINANCE' NOT NULL, \n\ttoken VARCHAR NOT NULL, \n\texpires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tused_at TIMESTAMP WITHOUT TIME ZONE, \n\tcreated_by VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_org_invites PRIMARY KEY (id), \n\tCONSTRAINT fk_org_invites_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tCONSTRAINT uq_org_invites_token UNIQUE (token), \n\tCONSTRAINT fk_org_invites_created_by_users FOREIGN KEY(created_by) REFERENCES users (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_org_invites_token ON org_invites (token)',
    'CREATE INDEX ix_org_invites_org_id ON org_invites (org_id)',
    "CREATE TABLE organization_memberships (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\trole org_role DEFAULT 'READONLY' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_organization_memberships PRIMARY KEY (id), \n\tCONSTRAINT uq_organization_memberships_org_id UNIQUE (org_id, user_id), \n\tCONSTRAINT fk_organization_memberships_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_organization_memberships_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)",
    'CREATE INDEX ix_organization_memberships_org_id ON organization_memberships (org_id)',
    'CREATE INDEX ix_organization_memberships_user_id ON organization_memberships (user_id)',
    'CREATE TABLE sessions (\n\tid VARCHAR NOT NULL, \n\tsession_token VARCHAR NOT NULL, \n\tuser_id VARCHAR NOT NULL, \n\texpires TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tCONSTRAINT pk_sessions PRIMARY KEY (id), \n\tCONSTRAINT uq_sessions_session_token UNIQUE (session_token), \n\tCONSTRAINT fk_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_sessions_user_id ON sessions (user_id)',
    'CREATE TABLE umlage_source_scopes (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tbeschreibung TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_umlage_source_scopes PRIMARY KEY (id), \n\tCONSTRAINT uq_umlage_source_scopes_org_id UNIQUE (org_id, name), \n\tCONSTRAINT fk_umlage_source_scopes_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_umlage_source_scopes_org_id ON umlage_source_scopes (org_id)',
    'CREATE TABLE allocation_key_positions (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tallocation_key_id VARCHAR NOT NULL, \n\tcost_center_id VARCHAR NOT NULL, \n\tprozent NUMERIC(6, 3) NOT NULL, \n\tCONSTRAINT pk_allocation_key_positions PRIMARY KEY (id), \n\tCONSTRAINT uq_allocation_key_positions_allocation_key_id UNIQUE (allocation_key_id, cost_center_id), \n\tCONSTRAINT fk_allocation_key_positions_allocation_key_id_allocation_keys FOREIGN KEY(allocation_key_id) REFERENCES allocation_keys (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_allocation_key_positions_cost_center_id_cost_centers FOREIGN KEY(cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_allocation_key_positions_org_id ON allocation_key_positions (org_id)',
    'CREATE INDEX ix_allocation_key_positions_allocation_key_id ON allocation_key_positions (allocation_key_id)',
    'CREATE TABLE employee_contracts (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\temployee_id VARCHAR NOT NULL, \n\tvertragsart vertragsart NOT NULL, \n\tassigned_hours NUMERIC(5, 2) NOT NULL, \n\tbase_salary NUMERIC(14, 2) NOT NULL, \n\ttarifwerk tarifwerk, \n\tentgeltgruppe VARCHAR(20), \n\tstufe INTEGER, \n\tgueltig_ab DATE NOT NULL, \n\tgueltig_bis DATE, \n\tnotiz TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_employee_contracts PRIMARY KEY (id), \n\tCONSTRAINT fk_employee_contracts_employee_id_employees FOREIGN KEY(employee_id) REFERENCES employees (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_employee_contracts_employee_id_gueltig_ab ON employee_contracts (employee_id, gueltig_ab)',
    'CREATE INDEX ix_employee_contracts_org_id ON employee_contracts (org_id)',
    'CREATE INDEX ix_employee_contracts_employee_id ON employee_contracts (employee_id)',
    'CREATE TABLE funder_nachweis_fristen (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunder_id VARCHAR NOT NULL, \n\tnachweis_typ verwendungsnachweis_typ NOT NULL, \n\tbezug frist_bezug NOT NULL, \n\ttage_offset INTEGER NOT NULL, \n\tbeschreibung TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_funder_nachweis_fristen PRIMARY KEY (id), \n\tCONSTRAINT uq_funder_nachweis_fristen_org_id UNIQUE (org_id, funder_id, nachweis_typ), \n\tCONSTRAINT fk_funder_nachweis_fristen_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_funder_nachweis_fristen_funder_id_funders FOREIGN KEY(funder_id) REFERENCES funders (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_funder_nachweis_fristen_org_id_funder_id ON funder_nachweis_fristen (org_id, funder_id)',
    "CREATE TABLE funding_measures (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunder_id VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tbudget_gesamt NUMERIC(14, 2) NOT NULL, \n\tfoerderquote NUMERIC(5, 2) NOT NULL, \n\tlaufzeit_von DATE NOT NULL, \n\tlaufzeit_bis DATE NOT NULL, \n\tdurchfuehrungs_von DATE, \n\tdurchfuehrungs_bis DATE, \n\tantragsnummer VARCHAR(100), \n\tverwaltungspauschale_erlaubt BOOLEAN DEFAULT 'false' NOT NULL, \n\tverwaltungspauschale_prozent NUMERIC(5, 2), \n\tbudget_flexibilitaet_prozent NUMERIC(5, 2) DEFAULT '20' NOT NULL, \n\toverhead_limit_prozent NUMERIC(5, 2), \n\tmwst_foerderfahig BOOLEAN DEFAULT 'true' NOT NULL, \n\tmwst_satz_prozent NUMERIC(5, 2) DEFAULT '19.0' NOT NULL, \n\tmittelabruf_verfahren mittelabruf_verfahren NOT NULL, \n\tstatus funding_measure_status DEFAULT 'AKTIV' NOT NULL, \n\tfoerderkennzeichen VARCHAR(100), \n\tfinanzierungsart finanzierungsart_typ, \n\teigenanteil_typ eigenanteil_typ, \n\teigenmittel_betrag NUMERIC(14, 2), \n\tdrittmittel_betrag NUMERIC(14, 2), \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_funding_measures PRIMARY KEY (id), \n\tCONSTRAINT fk_funding_measures_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_funding_measures_funder_id_funders FOREIGN KEY(funder_id) REFERENCES funders (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_funding_measures_org_id_foerderkennzeichen ON funding_measures (org_id, foerderkennzeichen)',
    'CREATE INDEX ix_funding_measures_org_id_status ON funding_measures (org_id, status)',
    'CREATE INDEX ix_funding_measures_org_id_antragsnummer ON funding_measures (org_id, antragsnummer)',
    'CREATE INDEX ix_funding_measures_org_id_funder_id ON funding_measures (org_id, funder_id)',
    'CREATE INDEX ix_funding_measures_org_id_laufzeit_bis ON funding_measures (org_id, laufzeit_bis)',
    'CREATE INDEX ix_funding_measures_org_id ON funding_measures (org_id)',
    "CREATE TABLE import_batches (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfiscal_year_id VARCHAR NOT NULL, \n\tformat import_format NOT NULL, \n\tcsv_import_profile_id VARCHAR, \n\tdateiname VARCHAR NOT NULL, \n\tanzahl_importiert INTEGER DEFAULT '0' NOT NULL, \n\tanzahl_duplikate INTEGER DEFAULT '0' NOT NULL, \n\tanzahl_fehler INTEGER DEFAULT '0' NOT NULL, \n\timport_log TEXT, \n\timportiert_von VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_import_batches PRIMARY KEY (id), \n\tCONSTRAINT fk_import_batches_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_import_batches_fiscal_year_id_fiscal_years FOREIGN KEY(fiscal_year_id) REFERENCES fiscal_years (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_import_batches_csv_import_profile_id_csv_import_profiles FOREIGN KEY(csv_import_profile_id) REFERENCES csv_import_profiles (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_import_batches_org_id ON import_batches (org_id)',
    'CREATE INDEX ix_import_batches_org_id_fiscal_year_id ON import_batches (org_id, fiscal_year_id)',
    "CREATE TABLE monthly_payrolls (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\temployee_id VARCHAR NOT NULL, \n\tfiscal_year_id VARCHAR NOT NULL, \n\tmonat DATE NOT NULL, \n\tassigned_hours NUMERIC(5, 2) NOT NULL, \n\tstandard_hours NUMERIC(5, 2) NOT NULL, \n\tbase_salary NUMERIC(14, 2) NOT NULL, \n\tag_faktor NUMERIC(6, 4) NOT NULL, \n\tactual_salary NUMERIC(14, 2) NOT NULL, \n\tbetrag_an_brutto NUMERIC(14, 2) NOT NULL, \n\tbetrag_ag_brutto NUMERIC(14, 2) NOT NULL, \n\tquelle VARCHAR DEFAULT 'MANUELL' NOT NULL, \n\timport_batch_id VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_monthly_payrolls PRIMARY KEY (id), \n\tCONSTRAINT uq_monthly_payrolls_org_id UNIQUE (org_id, employee_id, monat), \n\tCONSTRAINT fk_monthly_payrolls_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_monthly_payrolls_employee_id_employees FOREIGN KEY(employee_id) REFERENCES employees (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_monthly_payrolls_fiscal_year_id_fiscal_years FOREIGN KEY(fiscal_year_id) REFERENCES fiscal_years (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_monthly_payrolls_org_id ON monthly_payrolls (org_id)',
    'CREATE INDEX ix_monthly_payrolls_org_id_fiscal_year_id ON monthly_payrolls (org_id, fiscal_year_id)',
    'CREATE INDEX ix_monthly_payrolls_employee_id_monat ON monthly_payrolls (employee_id, monat)',
    'CREATE TABLE opening_balances (\n\tid VARCHAR NOT NULL, \n\tbank_account_id VARCHAR NOT NULL, \n\tfiscal_year_id VARCHAR NOT NULL, \n\tsaldo_eroeffnung NUMERIC(15, 2) NOT NULL, \n\tdatum DATE NOT NULL, \n\tnotiz TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_opening_balances PRIMARY KEY (id), \n\tCONSTRAINT uq_opening_balances_bank_account_id UNIQUE (bank_account_id, fiscal_year_id), \n\tCONSTRAINT fk_opening_balances_bank_account_id_bank_accounts FOREIGN KEY(bank_account_id) REFERENCES bank_accounts (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_opening_balances_fiscal_year_id_fiscal_years FOREIGN KEY(fiscal_year_id) REFERENCES fiscal_years (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_opening_balances_fiscal_year_id ON opening_balances (fiscal_year_id)',
    'CREATE TABLE umlage_source_scope_cost_centers (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tumlage_source_scope_id VARCHAR NOT NULL, \n\tcost_center_id VARCHAR NOT NULL, \n\tCONSTRAINT pk_umlage_source_scope_cost_centers PRIMARY KEY (id), \n\tCONSTRAINT uq_umlage_source_scope_cost_centers_umlage_source_scope_id UNIQUE (umlage_source_scope_id, cost_center_id), \n\tCONSTRAINT fk_umlage_source_scope_cost_centers_umlage_source_scope_9972 FOREIGN KEY(umlage_source_scope_id) REFERENCES umlage_source_scopes (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_umlage_source_scope_cost_centers_cost_center_id_cost_centers FOREIGN KEY(cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_umlage_source_scope_cost_centers_cost_center_id ON umlage_source_scope_cost_centers (cost_center_id)',
    'CREATE INDEX ix_umlage_source_scope_cost_centers_org_id ON umlage_source_scope_cost_centers (org_id)',
    "CREATE TABLE bescheid_dokumente (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tfilename VARCHAR(255) NOT NULL, \n\tmime_type VARCHAR(100) NOT NULL, \n\tsize_bytes INTEGER NOT NULL, \n\tbytes BYTEA NOT NULL, \n\tuploaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tquelle bescheid_quelle DEFAULT 'MANUAL_UPLOAD' NOT NULL, \n\tCONSTRAINT pk_bescheid_dokumente PRIMARY KEY (id), \n\tCONSTRAINT fk_bescheid_dokumente_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_bescheid_dokumente_funding_measure_id UNIQUE (funding_measure_id), \n\tCONSTRAINT fk_bescheid_dokumente_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE CASCADE\n)",
    'CREATE INDEX ix_bescheid_dokumente_org_id ON bescheid_dokumente (org_id)',
    "CREATE TABLE booking_rules (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\taktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tprioritaet INTEGER DEFAULT '0' NOT NULL, \n\tmatch_auftraggeber VARCHAR(200), \n\tmatch_auftraggeber_exact BOOLEAN DEFAULT 'false' NOT NULL, \n\tmatch_verwendungszweck VARCHAR(200), \n\tmatch_kostenbereich_id VARCHAR, \n\tmatch_iban_partner VARCHAR(34), \n\tmatch_betrag_min NUMERIC(14, 2), \n\tmatch_betrag_max NUMERIC(14, 2), \n\tmatch_datum_von DATE, \n\tmatch_datum_bis DATE, \n\tset_kostenbereich_id VARCHAR, \n\tmatch_count INTEGER DEFAULT '0' NOT NULL, \n\tconfidence VARCHAR(10) DEFAULT 'ORANGE' NOT NULL, \n\tfunding_measure_id VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_booking_rules PRIMARY KEY (id), \n\tCONSTRAINT fk_booking_rules_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_booking_rules_match_kostenbereich_id_kostenbereiche FOREIGN KEY(match_kostenbereich_id) REFERENCES kostenbereiche (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_booking_rules_set_kostenbereich_id_kostenbereiche FOREIGN KEY(set_kostenbereich_id) REFERENCES kostenbereiche (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_booking_rules_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_booking_rules_org_id_aktiv ON booking_rules (org_id, aktiv)',
    'CREATE INDEX ix_booking_rules_funding_measure_id ON booking_rules (funding_measure_id)',
    'CREATE INDEX ix_booking_rules_match_kostenbereich_id ON booking_rules (match_kostenbereich_id)',
    'CREATE INDEX ix_booking_rules_set_kostenbereich_id ON booking_rules (set_kostenbereich_id)',
    "CREATE TABLE finanzplan_positionen (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tpositionscode VARCHAR(50) NOT NULL, \n\tbezeichnung VARCHAR(500) NOT NULL, \n\tbetrag_bewilligt NUMERIC(14, 2) NOT NULL, \n\tdeckungsfaehigkeit_pool VARCHAR(100), \n\tueberziehung_limit_pct NUMERIC(5, 2) DEFAULT '20' NOT NULL, \n\tueberziehung_genehmigungspflichtig BOOLEAN DEFAULT 'false' NOT NULL, \n\tfoerderfahigkeit_hinweis TEXT, \n\teigenanteil_typ eigenanteil_typ, \n\tist_pauschale BOOLEAN DEFAULT 'false' NOT NULL, \n\tpauschale_typ pauschale_typ, \n\tpauschale_prozent NUMERIC(5, 2), \n\tumlage_allocation_key_id VARCHAR, \n\tumlage_ziel_cost_center_id VARCHAR, \n\tumlage_source_scope_id VARCHAR, \n\tsort_order INTEGER DEFAULT '0' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_finanzplan_positionen PRIMARY KEY (id), \n\tCONSTRAINT uq_finanzplan_positionen_funding_measure_id UNIQUE (funding_measure_id, positionscode), \n\tCONSTRAINT fk_finanzplan_positionen_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_finanzplan_positionen_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_finanzplan_positionen_umlage_allocation_key_id_alloc_8748 FOREIGN KEY(umlage_allocation_key_id) REFERENCES allocation_keys (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_finanzplan_positionen_umlage_ziel_cost_center_id_cos_5633 FOREIGN KEY(umlage_ziel_cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_finanzplan_positionen_umlage_source_scope_id_umlage__2924 FOREIGN KEY(umlage_source_scope_id) REFERENCES umlage_source_scopes (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_finanzplan_positionen_org_id ON finanzplan_positionen (org_id)',
    'CREATE INDEX ix_finanzplan_positionen_funding_measure_id ON finanzplan_positionen (funding_measure_id)',
    'CREATE INDEX ix_finanzplan_positionen_org_id_deckungsfaehigkeit_pool ON finanzplan_positionen (org_id, deckungsfaehigkeit_pool)',
    'CREATE INDEX ix_finanzplan_positionen_umlage_source_scope_id ON finanzplan_positionen (umlage_source_scope_id)',
    'CREATE TABLE funding_measure_cost_centers (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tcost_center_id VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_funding_measure_cost_centers PRIMARY KEY (id), \n\tCONSTRAINT uq_funding_measure_cost_centers_funding_measure_id UNIQUE (funding_measure_id, cost_center_id), \n\tCONSTRAINT fk_funding_measure_cost_centers_funding_measure_id_fund_9a25 FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_funding_measure_cost_centers_cost_center_id_cost_centers FOREIGN KEY(cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_funding_measure_cost_centers_funding_measure_id ON funding_measure_cost_centers (funding_measure_id)',
    'CREATE INDEX ix_funding_measure_cost_centers_cost_center_id ON funding_measure_cost_centers (cost_center_id)',
    'CREATE INDEX ix_funding_measure_cost_centers_org_id ON funding_measure_cost_centers (org_id)',
    'CREATE TABLE funding_rules (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\ttyp funding_rule_typ NOT NULL, \n\tschluessel VARCHAR NOT NULL, \n\twert TEXT, \n\tbeschreibung TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_funding_rules PRIMARY KEY (id), \n\tCONSTRAINT fk_funding_rules_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_funding_rules_funding_measure_id_typ ON funding_rules (funding_measure_id, typ)',
    'CREATE INDEX ix_funding_rules_org_id ON funding_rules (org_id)',
    'CREATE INDEX ix_funding_rules_funding_measure_id ON funding_rules (funding_measure_id)',
    "CREATE TABLE mittelabrufe (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tfiscal_year_id VARCHAR NOT NULL, \n\tabruf_datum DATE NOT NULL, \n\tbetrag NUMERIC(14, 2) NOT NULL, \n\tverwendungsfrist_tage INTEGER DEFAULT '42' NOT NULL, \n\tfrist_bis DATE NOT NULL, \n\tstatus mittelabruf_status DEFAULT 'ABGERUFEN' NOT NULL, \n\tbetrag_verwendet NUMERIC(14, 2) DEFAULT '0' NOT NULL, \n\tbetrag_zurueck NUMERIC(14, 2), \n\tnotiz TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_mittelabrufe PRIMARY KEY (id), \n\tCONSTRAINT fk_mittelabrufe_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_mittelabrufe_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_mittelabrufe_fiscal_year_id_fiscal_years FOREIGN KEY(fiscal_year_id) REFERENCES fiscal_years (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_mittelabrufe_frist_bis ON mittelabrufe (frist_bis)',
    'CREATE INDEX ix_mittelabrufe_org_id ON mittelabrufe (org_id)',
    'CREATE INDEX ix_mittelabrufe_org_id_funding_measure_id ON mittelabrufe (org_id, funding_measure_id)',
    'CREATE INDEX ix_mittelabrufe_org_id_status ON mittelabrufe (org_id, status)',
    "CREATE TABLE nachweis_templates (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tprogramm_typ VARCHAR(100) NOT NULL, \n\tdatei_pfad VARCHAR(500) NOT NULL, \n\tdatei_name VARCHAR(255) NOT NULL, \n\tdatei_typ VARCHAR(50) NOT NULL, \n\tfeld_mappings JSONB DEFAULT '{}' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_nachweis_templates PRIMARY KEY (id), \n\tCONSTRAINT fk_nachweis_templates_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT uq_nachweis_templates_funding_measure_id UNIQUE (funding_measure_id), \n\tCONSTRAINT fk_nachweis_templates_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE CASCADE\n)",
    'CREATE INDEX ix_nachweis_templates_org_id ON nachweis_templates (org_id)',
    'CREATE TABLE payroll_components (\n\tid VARCHAR NOT NULL, \n\tpayroll_id VARCHAR NOT NULL, \n\ttyp salary_component_typ NOT NULL, \n\tbezeichnung VARCHAR(100) NOT NULL, \n\tbetrag NUMERIC(14, 2) NOT NULL, \n\tnach_multiplikator BOOLEAN NOT NULL, \n\tCONSTRAINT pk_payroll_components PRIMARY KEY (id), \n\tCONSTRAINT fk_payroll_components_payroll_id_monthly_payrolls FOREIGN KEY(payroll_id) REFERENCES monthly_payrolls (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_payroll_components_payroll_id ON payroll_components (payroll_id)',
    "CREATE TABLE salary_components (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tcontract_id VARCHAR NOT NULL, \n\ttyp salary_component_typ NOT NULL, \n\tbezeichnung VARCHAR(100) NOT NULL, \n\tbetrag NUMERIC(14, 2) NOT NULL, \n\tnach_multiplikator BOOLEAN DEFAULT 'false' NOT NULL, \n\teinmalig BOOLEAN DEFAULT 'false' NOT NULL, \n\tgilt_fuer_monat DATE, \n\tist_aktiv BOOLEAN DEFAULT 'true' NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_salary_components PRIMARY KEY (id), \n\tCONSTRAINT fk_salary_components_contract_id_employee_contracts FOREIGN KEY(contract_id) REFERENCES employee_contracts (id) ON DELETE CASCADE\n)",
    'CREATE INDEX ix_salary_components_org_id ON salary_components (org_id)',
    'CREATE INDEX ix_salary_components_contract_id ON salary_components (contract_id)',
    "CREATE TABLE transactions (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfiscal_year_id VARCHAR NOT NULL, \n\timport_batch_id VARCHAR, \n\tbank_account_id VARCHAR, \n\tdatum DATE NOT NULL, \n\tvaluta_datum DATE, \n\tbetrag NUMERIC(14, 2) NOT NULL, \n\tsaldo_nach_buchung NUMERIC(15, 2), \n\ttyp transaction_typ NOT NULL, \n\tauftraggeber VARCHAR(255), \n\tiban_partner VARCHAR(34), \n\tbic_partner VARCHAR(11), \n\tverwendungszweck TEXT, \n\texterne_referenz VARCHAR(100), \n\tglaeubiger_id VARCHAR(35), \n\tmandatsreferenz VARCHAR(35), \n\tbuchungstext_typ VARCHAR(80), \n\tkostenbereich_id VARCHAR, \n\tnotiz TEXT, \n\tstatus transaction_status DEFAULT 'IMPORTIERT' NOT NULL, \n\tduplikat_hash VARCHAR(64), \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_transactions PRIMARY KEY (id), \n\tCONSTRAINT fk_transactions_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_transactions_fiscal_year_id_fiscal_years FOREIGN KEY(fiscal_year_id) REFERENCES fiscal_years (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_transactions_import_batch_id_import_batches FOREIGN KEY(import_batch_id) REFERENCES import_batches (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_transactions_bank_account_id_bank_accounts FOREIGN KEY(bank_account_id) REFERENCES bank_accounts (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_transactions_kostenbereich_id_kostenbereiche FOREIGN KEY(kostenbereich_id) REFERENCES kostenbereiche (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_transactions_org_id_bank_account_id ON transactions (org_id, bank_account_id)',
    'CREATE INDEX ix_transactions_org_id_datum ON transactions (org_id, datum)',
    'CREATE INDEX ix_transactions_org_id ON transactions (org_id)',
    'CREATE INDEX ix_transactions_org_id_iban_partner ON transactions (org_id, iban_partner)',
    'CREATE INDEX ix_transactions_duplikat_hash ON transactions (duplikat_hash)',
    'CREATE INDEX ix_transactions_org_id_fiscal_year_id ON transactions (org_id, fiscal_year_id)',
    'CREATE INDEX ix_transactions_org_id_kostenbereich_id ON transactions (org_id, kostenbereich_id)',
    'CREATE INDEX ix_transactions_org_id_status ON transactions (org_id, status)',
    "CREATE TABLE verwendungsnachweise (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tfiscal_year_id VARCHAR NOT NULL, \n\tzeitraum_von DATE NOT NULL, \n\tzeitraum_bis DATE NOT NULL, \n\tfrist DATE NOT NULL, \n\ttyp verwendungsnachweis_typ NOT NULL, \n\tstatus verwendungsnachweis_status DEFAULT 'OFFEN' NOT NULL, \n\tsnapshot_json JSONB, \n\tnotiz TEXT, \n\teingereicht_am TIMESTAMP WITHOUT TIME ZONE, \n\teingereicht_von VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_verwendungsnachweise PRIMARY KEY (id), \n\tCONSTRAINT fk_verwendungsnachweise_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_verwendungsnachweise_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_verwendungsnachweise_fiscal_year_id_fiscal_years FOREIGN KEY(fiscal_year_id) REFERENCES fiscal_years (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_verwendungsnachweise_org_id_funding_measure_id ON verwendungsnachweise (org_id, funding_measure_id)',
    'CREATE INDEX ix_verwendungsnachweise_org_id_status ON verwendungsnachweise (org_id, status)',
    'CREATE INDEX ix_verwendungsnachweise_frist ON verwendungsnachweise (frist)',
    'CREATE INDEX ix_verwendungsnachweise_org_id ON verwendungsnachweise (org_id)',
    'CREATE TABLE booking_rule_applications (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\ttransaction_id VARCHAR NOT NULL, \n\trule_id VARCHAR NOT NULL, \n\tapplied_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tapplied_by VARCHAR, \n\tconfidence VARCHAR(10) NOT NULL, \n\tCONSTRAINT pk_booking_rule_applications PRIMARY KEY (id), \n\tCONSTRAINT fk_booking_rule_applications_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_booking_rule_applications_transaction_id_transactions FOREIGN KEY(transaction_id) REFERENCES transactions (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_booking_rule_applications_rule_id_booking_rules FOREIGN KEY(rule_id) REFERENCES booking_rules (id) ON DELETE CASCADE\n)',
    'CREATE INDEX ix_booking_rule_applications_transaction_id ON booking_rule_applications (transaction_id)',
    'CREATE INDEX ix_booking_rule_applications_rule_id ON booking_rule_applications (rule_id)',
    'CREATE INDEX ix_booking_rule_applications_org_id ON booking_rule_applications (org_id)',
    'CREATE TABLE booking_rule_splits (\n\tid VARCHAR NOT NULL, \n\trule_id VARCHAR NOT NULL, \n\tcost_center_id VARCHAR NOT NULL, \n\tprozent NUMERIC(6, 3) NOT NULL, \n\tallocation_key_id VARCHAR, \n\tfunding_measure_id VARCHAR, \n\tallocation_prozent NUMERIC(5, 2), \n\tCONSTRAINT pk_booking_rule_splits PRIMARY KEY (id), \n\tCONSTRAINT fk_booking_rule_splits_rule_id_booking_rules FOREIGN KEY(rule_id) REFERENCES booking_rules (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_booking_rule_splits_cost_center_id_cost_centers FOREIGN KEY(cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_booking_rule_splits_allocation_key_id_allocation_keys FOREIGN KEY(allocation_key_id) REFERENCES allocation_keys (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_booking_rule_splits_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE SET NULL\n)',
    'CREATE INDEX ix_booking_rule_splits_rule_id ON booking_rule_splits (rule_id)',
    'CREATE INDEX ix_booking_rule_splits_funding_measure_id ON booking_rule_splits (funding_measure_id)',
    "CREATE TABLE finanzplan_position_kostenbereiche (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfinanzplan_position_id VARCHAR NOT NULL, \n\tkostenbereich_id VARCHAR NOT NULL, \n\tfoerderfahig_anteil NUMERIC(5, 4) DEFAULT '1' NOT NULL, \n\tcap_betrag NUMERIC(14, 2), \n\thinweis TEXT, \n\tCONSTRAINT pk_finanzplan_position_kostenbereiche PRIMARY KEY (id), \n\tCONSTRAINT uq_finanzplan_position_kostenbereiche_finanzplan_position_id UNIQUE (finanzplan_position_id, kostenbereich_id), \n\tCONSTRAINT fk_finanzplan_position_kostenbereiche_finanzplan_positi_9acb FOREIGN KEY(finanzplan_position_id) REFERENCES finanzplan_positionen (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_finanzplan_position_kostenbereiche_kostenbereich_id__e640 FOREIGN KEY(kostenbereich_id) REFERENCES kostenbereiche (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_finanzplan_position_kostenbereiche_org_id ON finanzplan_position_kostenbereiche (org_id)',
    'CREATE INDEX ix_finanzplan_position_kostenbereiche_finanzplan_position_id ON finanzplan_position_kostenbereiche (finanzplan_position_id)',
    'CREATE INDEX ix_finanzplan_position_kostenbereiche_kostenbereich_id ON finanzplan_position_kostenbereiche (kostenbereich_id)',
    "CREATE TABLE haushaltsplan_posten (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tfinanzplan_position_id VARCHAR NOT NULL, \n\tkostenbereich_id VARCHAR NOT NULL, \n\tfuer_monat DATE NOT NULL, \n\tbetrag_geplant NUMERIC(14, 2) NOT NULL, \n\tquelle VARCHAR(50) DEFAULT 'MANUELL' NOT NULL, \n\tbeschreibung TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_haushaltsplan_posten PRIMARY KEY (id), \n\tCONSTRAINT uq_haushaltsplan_posten_funding_measure_id UNIQUE (funding_measure_id, finanzplan_position_id, kostenbereich_id, fuer_monat), \n\tCONSTRAINT fk_haushaltsplan_posten_org_id_organizations FOREIGN KEY(org_id) REFERENCES organizations (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_haushaltsplan_posten_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_haushaltsplan_posten_finanzplan_position_id_finanzpl_0408 FOREIGN KEY(finanzplan_position_id) REFERENCES finanzplan_positionen (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_haushaltsplan_posten_kostenbereich_id_kostenbereiche FOREIGN KEY(kostenbereich_id) REFERENCES kostenbereiche (id) ON DELETE RESTRICT\n)",
    'CREATE INDEX ix_haushaltsplan_posten_org_id ON haushaltsplan_posten (org_id)',
    'CREATE INDEX ix_haushaltsplan_posten_funding_measure_id ON haushaltsplan_posten (funding_measure_id)',
    'CREATE INDEX ix_haushaltsplan_posten_finanzplan_position_id ON haushaltsplan_posten (finanzplan_position_id)',
    'CREATE INDEX ix_haushaltsplan_posten_org_id_fuer_monat ON haushaltsplan_posten (org_id, fuer_monat)',
    'CREATE TABLE payroll_allocations (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\tpayroll_id VARCHAR NOT NULL, \n\tcost_center_id VARCHAR NOT NULL, \n\tprozent NUMERIC(6, 3) NOT NULL, \n\tbetrag_anteil NUMERIC(14, 2) NOT NULL, \n\tallocation_key_id VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_payroll_allocations PRIMARY KEY (id), \n\tCONSTRAINT fk_payroll_allocations_payroll_id_monthly_payrolls FOREIGN KEY(payroll_id) REFERENCES monthly_payrolls (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_payroll_allocations_cost_center_id_cost_centers FOREIGN KEY(cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_payroll_allocations_allocation_key_id_allocation_keys FOREIGN KEY(allocation_key_id) REFERENCES allocation_keys (id) ON DELETE SET NULL\n)',
    'CREATE INDEX ix_payroll_allocations_cost_center_id ON payroll_allocations (cost_center_id)',
    'CREATE INDEX ix_payroll_allocations_org_id ON payroll_allocations (org_id)',
    'CREATE INDEX ix_payroll_allocations_payroll_id ON payroll_allocations (payroll_id)',
    'CREATE TABLE transaction_belege (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\ttransaction_id VARCHAR NOT NULL, \n\tdatei_pfad VARCHAR(500), \n\tdatei_name VARCHAR(255), \n\tdatei_typ VARCHAR(50), \n\texterne_referenz VARCHAR(100), \n\tretention_until DATE NOT NULL, \n\tgeloescht_am TIMESTAMP WITHOUT TIME ZONE, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_transaction_belege PRIMARY KEY (id), \n\tCONSTRAINT fk_transaction_belege_transaction_id_transactions FOREIGN KEY(transaction_id) REFERENCES transactions (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_transaction_belege_transaction_id ON transaction_belege (transaction_id)',
    'CREATE INDEX ix_transaction_belege_org_id ON transaction_belege (org_id)',
    'CREATE TABLE transaction_splits (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\ttransaction_id VARCHAR NOT NULL, \n\tcost_center_id VARCHAR NOT NULL, \n\tprozent NUMERIC(6, 3) NOT NULL, \n\tbetrag_anteil NUMERIC(14, 2) NOT NULL, \n\tallocation_key_id VARCHAR, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_transaction_splits PRIMARY KEY (id), \n\tCONSTRAINT fk_transaction_splits_transaction_id_transactions FOREIGN KEY(transaction_id) REFERENCES transactions (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_transaction_splits_cost_center_id_cost_centers FOREIGN KEY(cost_center_id) REFERENCES cost_centers (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_transaction_splits_allocation_key_id_allocation_keys FOREIGN KEY(allocation_key_id) REFERENCES allocation_keys (id) ON DELETE SET NULL\n)',
    'CREATE INDEX ix_transaction_splits_cost_center_id ON transaction_splits (cost_center_id)',
    'CREATE INDEX ix_transaction_splits_org_id ON transaction_splits (org_id)',
    'CREATE INDEX ix_transaction_splits_transaction_id ON transaction_splits (transaction_id)',
    "CREATE TABLE fund_allocations (\n\tid VARCHAR NOT NULL, \n\torg_id VARCHAR NOT NULL, \n\ttransaction_split_id VARCHAR NOT NULL, \n\tfunding_measure_id VARCHAR NOT NULL, \n\tprozent NUMERIC(5, 2) DEFAULT '100' NOT NULL, \n\tfinanzplan_position_id VARCHAR, \n\tbetrag_foerderfahig NUMERIC(14, 2) NOT NULL, \n\tbetrag_foerderung NUMERIC(14, 2) NOT NULL, \n\tbetrag_eigenanteil NUMERIC(14, 2) NOT NULL, \n\tstatus VARCHAR DEFAULT 'VORLAEUFIG' NOT NULL, \n\tnotiz TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_fund_allocations PRIMARY KEY (id), \n\tCONSTRAINT uq_fund_allocations_transaction_split_id UNIQUE (transaction_split_id, funding_measure_id), \n\tCONSTRAINT fk_fund_allocations_transaction_split_id_transaction_splits FOREIGN KEY(transaction_split_id) REFERENCES transaction_splits (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_fund_allocations_funding_measure_id_funding_measures FOREIGN KEY(funding_measure_id) REFERENCES funding_measures (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_fund_allocations_finanzplan_position_id_finanzplan_p_3660 FOREIGN KEY(finanzplan_position_id) REFERENCES finanzplan_positionen (id) ON DELETE SET NULL\n)",
    'CREATE INDEX ix_fund_allocations_transaction_split_id ON fund_allocations (transaction_split_id)',
    'CREATE INDEX ix_fund_allocations_funding_measure_id ON fund_allocations (funding_measure_id)',
    'CREATE INDEX ix_fund_allocations_finanzplan_position_id ON fund_allocations (finanzplan_position_id)',
    'CREATE INDEX ix_fund_allocations_org_id ON fund_allocations (org_id)',
)

_DROP_STATEMENTS: tuple[str, ...] = (
    'DROP TABLE fund_allocations',
    'DROP TABLE transaction_splits',
    'DROP TABLE transaction_belege',
    'DROP TABLE payroll_allocations',
    'DROP TABLE haushaltsplan_posten',
    'DROP TABLE finanzplan_position_kostenbereiche',
    'DROP TABLE booking_rule_splits',
    'DROP TABLE booking_rule_applications',
    'DROP TABLE verwendungsnachweise',
    'DROP TABLE transactions',
    'DROP TABLE salary_components',
    'DROP TABLE payroll_components',
    'DROP TABLE nachweis_templates',
    'DROP TABLE mittelabrufe',
    'DROP TABLE funding_rules',
    'DROP TABLE funding_measure_cost_centers',
    'DROP TABLE finanzplan_positionen',
    'DROP TABLE booking_rules',
    'DROP TABLE bescheid_dokumente',
    'DROP TABLE umlage_source_scope_cost_centers',
    'DROP TABLE opening_balances',
    'DROP TABLE monthly_payrolls',
    'DROP TABLE import_batches',
    'DROP TABLE funding_measures',
    'DROP TABLE funder_nachweis_fristen',
    'DROP TABLE employee_contracts',
    'DROP TABLE allocation_key_positions',
    'DROP TABLE umlage_source_scopes',
    'DROP TABLE sessions',
    'DROP TABLE organization_memberships',
    'DROP TABLE org_invites',
    'DROP TABLE kostenbereiche',
    'DROP TABLE funders',
    'DROP TABLE fiscal_years',
    'DROP TABLE employer_gross_factors',
    'DROP TABLE employees',
    'DROP TABLE csv_import_profiles',
    'DROP TABLE cost_centers',
    'DROP TABLE bank_accounts',
    'DROP TABLE allocation_keys',
    'DROP TABLE accounts',
    'DROP TABLE verification_tokens',
    'DROP TABLE users',
    'DROP TABLE tarif_tabelle',
    'DROP TABLE organizations',
    'DROP TABLE audit_logs',
    'DROP TYPE allocation_basis',
    'DROP TYPE org_role',
    'DROP TYPE eigenanteil_typ',
    'DROP TYPE pauschale_typ',
    'DROP TYPE verwendungsnachweis_typ',
    'DROP TYPE verwendungsnachweis_status',
    'DROP TYPE mittelabruf_verfahren',
    'DROP TYPE funding_measure_status',
    'DROP TYPE finanzierungsart_typ',
    'DROP TYPE bescheid_quelle',
    'DROP TYPE funding_rule_typ',
    'DROP TYPE cost_center_typ',
    'DROP TYPE funder_typ',
    'DROP TYPE frist_bezug',
    'DROP TYPE fiscal_year_status',
    'DROP TYPE mittelabruf_status',
    'DROP TYPE rechtsform',
    'DROP TYPE vertragsart',
    'DROP TYPE tarifwerk',
    'DROP TYPE salary_component_typ',
    'DROP TYPE account_typ',
    'DROP TYPE import_format',
    'DROP TYPE transaction_typ',
    'DROP TYPE transaction_status',
)


def upgrade() -> None:
    for statement in _CREATE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for statement in _DROP_STATEMENTS:
        op.execute(statement)
