"""initial schema — full FörderFlow data model (46 tables, 24 enums)

Baseline migration. Builds the complete schema from the validated SQLAlchemy
metadata (a standard baseline pattern), guaranteeing the migration is byte-equal
to the ORM models. Subsequent changes use ordinary autogenerated revisions.

The schema preserves the monolith's Prisma `@@map` table/column names, native
PostgreSQL enum types, relationships, unique constraints and indexes, so this DB
is drop-in compatible with the original FörderFlow database.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-16
"""

from collections.abc import Sequence

from alembic import op

import app.models  # noqa: F401  (registers all tables on Base.metadata)
from app.db.base import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
