"""Module PCM monthly payroll engine.

Computes one employee's payroll for one month and writes the PCM-scoped rows:
``monthly_payrolls`` (quelle = PCM), ``payroll_detail_lines`` (BASE + BAV) and
``payroll_allocations`` (origin = PCM), distributing the employer cost across the
employee's active Wochenstundenzuweisungen.

Pipeline (Core-MVP subset of spec §2.2.13):
  1. Fiscal-year-open guard (CLOSED years are immutable).
  2. Re-run safety — replace only a prior PCM-generated payroll for the month;
     a manual payroll is never overwritten.
  3. Resolve base salary + standard hours via the tariff validity window (picks
     up mid-year tariff splits), else the contract + org regular hours.
  4. Dreisatz proration (reusing berechne_gehalt) → actual_salary, AN/AG-Brutto.
  5. BAV (employer pension, flat rate) added to AG-Brutto.
  6. Write detail lines + hour-proportional PCM allocations.

Bonuses, salary adjustments, leave, JSZ/REFERENCE_MONTH and external imports are
later phases (their tables were deliberately deferred in Phase 1).
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal

from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from app.core.errors import APIError
from app.models.enums import (
    AllocationOrigin,
    BruttoType,
    FiscalYearStatus,
    PayrollDetailComponent,
    PayrollStatus,
)
from app.models.master import FiscalYear
from app.models.organization import Organization
from app.models.payroll import Employee, MonthlyPayroll, PayrollAllocation
from app.models.pcm_payroll import PayrollDetailLine
from app.models.pcm_personnel import WochenstundenZuweisung
from app.models.pcm_tariff import SalaryTariff
from app.services.pcm.bonus_engine import compute_extra_components
from app.services.pcm.calc import compute_bav, round2
from app.services.pcm.leave_service import is_on_leave
from app.services.pcm.period_service import assert_period_not_locked
from app.services.pcm.tariff_lookup import resolve_tariff
from app.services.personal.berechnung import (
    berechne_gehalt,
    get_ag_faktor,
    get_aktiver_vertrag,
)

# Marks payroll rows generated by the PCM engine (vs. "MANUELL" manual entry).
PCM_QUELLE = "PCM"


def _active_assignments(
    db: Session, *, org_id: str, employee_id: str, monat: date
) -> list[WochenstundenZuweisung]:
    return (
        db.execute(
            select(WochenstundenZuweisung).where(
                WochenstundenZuweisung.org_id == org_id,
                WochenstundenZuweisung.employee_id == employee_id,
                WochenstundenZuweisung.effective_date <= monat,
                or_(
                    WochenstundenZuweisung.end_date.is_(None),
                    WochenstundenZuweisung.end_date >= monat,
                ),
            )
        )
        .scalars()
        .all()
    )


def run_monthly_payroll(
    db: Session,
    *,
    org_id: str,
    employee_id: str,
    fiscal_year_id: str,
    monat: date,
) -> MonthlyPayroll:
    """Run (or re-run) the PCM payroll for one employee and month. Commits."""
    fy = db.get(FiscalYear, fiscal_year_id)
    if fy is None or fy.org_id != org_id:
        raise APIError(404, "NOT_FOUND", "Haushaltsjahr nicht gefunden.")
    if fy.status == FiscalYearStatus.GESCHLOSSEN:
        raise APIError(
            409,
            "FISCAL_YEAR_CLOSED",
            "Das Haushaltsjahr ist geschlossen — keine PCM-Abrechnung möglich.",
        )
    # A LOCKED payroll period is frozen — no run / re-run (Area I.7).
    assert_period_not_locked(db, org_id=org_id, monat=monat)

    # Re-run safety: replace a prior PCM payroll; never clobber a manual one.
    existing = db.execute(
        select(MonthlyPayroll).where(
            MonthlyPayroll.org_id == org_id,
            MonthlyPayroll.employee_id == employee_id,
            MonthlyPayroll.monat == monat,
        )
    ).scalar_one_or_none()
    if existing is not None:
        if existing.quelle != PCM_QUELLE:
            raise APIError(
                409,
                "PAYROLL_EXISTS_MANUAL",
                "Für diesen Monat existiert bereits eine manuelle Abrechnung — "
                "der PCM-Lauf überschreibt sie nicht.",
            )
        db.delete(existing)  # cascades allocations, components, detail lines
        db.flush()

    # Leave suppression: an employee on active leave for the month produces a
    # zero-gross ON_LEAVE row (no detail lines, no allocations) instead of a calc.
    leave = is_on_leave(db, org_id=org_id, employee_id=employee_id, month=monat)
    if leave is not None:
        payroll = MonthlyPayroll(
            org_id=org_id,
            employee_id=employee_id,
            fiscal_year_id=fiscal_year_id,
            monat=monat,
            assigned_hours=Decimal("0.00"),
            standard_hours=Decimal("0.00"),
            base_salary=Decimal("0.00"),
            ag_faktor=Decimal("0.0000"),
            actual_salary=Decimal("0.00"),
            betrag_an_brutto=Decimal("0.00"),
            betrag_ag_brutto=Decimal("0.00"),
            bav_amount=Decimal("0.00"),
            fringe_benefits_amount=Decimal("0.00"),
            status=PayrollStatus.ON_LEAVE,
            quelle=PCM_QUELLE,
        )
        db.add(payroll)
        db.commit()
        db.refresh(payroll)
        return payroll

    contract = get_aktiver_vertrag(db, employee_id, monat)
    if contract is None:
        raise APIError(
            422, "NO_CONTRACT", "Kein aktiver Vertrag für diesen Monat gefunden."
        )

    assignments = _active_assignments(
        db, org_id=org_id, employee_id=employee_id, monat=monat
    )
    if not assignments:
        raise APIError(
            422,
            "NO_HOUR_ASSIGNMENTS",
            "Keine aktiven Wochenstunden-Zuweisungen für diesen Monat.",
        )
    project_hours = sum(float(a.weekly_hours) for a in assignments)

    # Base salary + standard hours from the tariff validity window (mid-year
    # splits resolve automatically), else the contract + org regular hours.
    tariff = None
    if contract.salary_tariff_id:
        linked = db.get(SalaryTariff, contract.salary_tariff_id)
        if linked is not None:
            tariff = (
                resolve_tariff(
                    db,
                    org_id=org_id,
                    tariff_code=linked.tariff_code,
                    salary_group=linked.salary_group,
                    level=linked.level,
                    month=monat,
                )
                or linked
            )
    org = db.get(Organization, org_id)
    org_bav = float(org.bav_rate_pct or 0)  # org default when no tariff override
    if tariff is not None:
        base_full_time = float(tariff.monthly_amount)
        standard_hours = float(tariff.standard_hours)
        bav_rate = float(tariff.bav_rate_pct) if tariff.bav_rate_pct is not None else org_bav
    else:
        base_full_time = float(contract.base_salary)
        standard_hours = float(org.regelarbeitszeit_stunden)
        bav_rate = org_bav

    vertragsart = (
        contract.vertragsart.value
        if hasattr(contract.vertragsart, "value")
        else contract.vertragsart
    )
    ag_faktor = get_ag_faktor(db, org_id, vertragsart, monat)
    calc = berechne_gehalt(
        base_salary=base_full_time,
        assigned_hours=project_hours,
        standard_hours=standard_hours,
        ag_faktor=ag_faktor,
        components=[],
    )
    bav_amount = compute_bav(actual_salary=calc.actual_salary, bav_rate_pct=bav_rate)
    an_brutto = calc.an_brutto
    ag_brutto = calc.ag_brutto + bav_amount  # BAV is an employer cost

    # Bonuses, templates and salary adjustments (Areas G & H) → detail lines and
    # brutto deltas (EMPLOYER → AG · EMPLOYEE → AN+AG · NEITHER → fringe).
    employee = db.get(Employee, employee_id)
    extra = compute_extra_components(
        db,
        org_id=org_id,
        employee=employee,
        contract=contract,
        month=monat,
        actual_salary=calc.actual_salary,
        project_hours=project_hours,
        standard_hours=standard_hours,
        assignments=assignments,
    )
    fringe = 0.0
    for line in extra:
        amt = float(line.amount)
        if line.brutto_type == BruttoType.EMPLOYER:
            ag_brutto += amt
        elif line.brutto_type == BruttoType.EMPLOYEE:
            an_brutto += amt
            ag_brutto += amt
        else:  # NEITHER → fringe benefit, in neither brutto
            fringe += amt

    payroll = MonthlyPayroll(
        org_id=org_id,
        employee_id=employee_id,
        fiscal_year_id=fiscal_year_id,
        monat=monat,
        assigned_hours=round2(project_hours),
        standard_hours=round2(standard_hours),
        base_salary=round2(base_full_time),
        ag_faktor=Decimal(str(ag_faktor)),
        actual_salary=round2(calc.actual_salary),
        betrag_an_brutto=round2(an_brutto),
        betrag_ag_brutto=round2(ag_brutto),
        bav_amount=round2(bav_amount),
        fringe_benefits_amount=round2(fringe),
        status=PayrollStatus.CALCULATED,
        quelle=PCM_QUELLE,
    )
    db.add(payroll)
    db.flush()

    # Detail lines — the VWN itemization spine (BASE always, BAV when present).
    db.add(
        PayrollDetailLine(
            org_id=org_id,
            monthly_payroll_id=payroll.id,
            component=PayrollDetailComponent.BASE,
            description="Grundgehalt (anteilig)",
            amount=round2(calc.actual_salary),
            brutto_type=BruttoType.EMPLOYER,
        )
    )
    if bav_amount > 0:
        db.add(
            PayrollDetailLine(
                org_id=org_id,
                monthly_payroll_id=payroll.id,
                component=PayrollDetailComponent.BAV,
                description=f"BAV {bav_rate:.2f}%",
                amount=round2(bav_amount),
                brutto_type=BruttoType.EMPLOYER,
            )
        )
    for line in extra:
        db.add(
            PayrollDetailLine(
                org_id=org_id,
                monthly_payroll_id=payroll.id,
                component=line.component,
                description=line.description,
                amount=line.amount,
                brutto_type=line.brutto_type,
            )
        )

    # Allocations — AG-Brutto split across cost centres proportional to hours.
    for a in assignments:
        prozent = float(a.weekly_hours) / project_hours * 100.0
        db.add(
            PayrollAllocation(
                org_id=org_id,
                payroll_id=payroll.id,
                cost_center_id=a.cost_center_id,
                prozent=round2(prozent),
                betrag_anteil=round2(ag_brutto * prozent / 100.0),
                origin=AllocationOrigin.PCM,
                funding_measure_id=a.funding_measure_id,
                finanzplan_position_id=a.finanzplan_position_id,
            )
        )

    db.commit()
    db.refresh(payroll)
    return payroll
